[package]
name = "rsnotablog05"
version = "0.1.0"
edition = "2024"

[dependencies]
notionrs = { version = "0.7.0" }
notionrs_types = { version = "0.6.0" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tera = "1"
